added html and css file
Kossi-stack/My-Portfolio pull request #1
Opened 2021-07-08 18:58 UTC by Kossi-stack

I am requesting a review of my Portfolio setup and mobile version skeleton.

2021-07-08 19:19 UTC, hemant-soni-vst-au4 requested changes
Hello @Kossi-stack 👋
While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have a linter setup. Please follow the guidelines carefully. To setup linter follow this [link](https://github.com/microverseinc/linters-config/tree/master/html-css)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers,
Hemant Soni
Cheers and happy coding 😃

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. You can mention me (@hemant-soni-vst-au4) so I can see your comments and respond.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

------

2021-07-08 21:29 UTC, AshakaE requested changes
### Hi @Kossi-stack , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

# Required Changes ♻️

- [ ] Please fix the repeating background image issue
_Hint CSS no-repeat_

_Check the comments under the review._

###  Optional suggestions

- [ ] Please organize your image files into an assets folder and reference them from there.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2021-07-08 21:29 UTC, AshakaE commented on index.html
> +      <nav id="nav-bar">
- [ ] Kindly use a `header` tag to wrap all elements here, in this case you used a `nav` tag

2021-07-08 21:29 UTC, AshakaE commented on index.html
> +          </div>
- [ ] For the mobile version of the portfolio, it is only required that you create a menu icon, and wrap it in a `nav` tag. The menu icon should be a link as well
_Hint - fontawesome icons_

2021-07-09 00:31 UTC, arslanbisharat approved these changes
# Approved 👏 

Hi @Kossi-stack,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

2021-07-09 08:06 UTC, merged

2021-07-09 08:20 UTC, Kossi-stack commented
> 
> # Approved 👏
> 
> Hi @Kossi-stack,
> 
> Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
> Congratulations! 🎉
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

Good morning @arslanbisharat 

After you have approved my project yesterday, I was not able to submit it because it still showing changes required
Please can you check it at your side and reach out to me.

Thanks 😄